### ISSUE TITLE
Template for new TQ notes

### ISSUE THREAD

**Issue by liam5463** [tgrosinger/tq-obsidian#33] opened 2021-08-07 17:47 UTC
**Is your feature request related to a problem? Please describe.**
ability to add custom metadata to tasks

**Describe the solution you'd like**
ability to add custom metadata to tasks

**Describe alternatives you've considered**
template for new tq notes?
option to add custom metadata

**Additional context**

**Comment by tgrosinger** [comment] 2021-08-09 14:47
Hi @liam5463, I think this is a duplicate of #18.

**Closed** 2021-08-21 03:06 UTC
Labels: enhancement
